# Generated by Django 3.0.7 on 2020-07-01 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bvi', models.BooleanField()),
                ('application_date', models.DateField()),
                ('funded_only', models.BooleanField()),
                ('is_checked', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='abitur.School')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
    ]
