# Generated by Django 3.0.7 on 2020-07-01 18:50

from django.db import migrations


def add_schools(apps, schema_editor):
    school = apps.get_model('abitur', 'School')
    school.objects.create(name='Сеченовка')
    school.objects.create(name='Пироговка')


class Migration(migrations.Migration):

    dependencies = [
        ('abitur', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_schools)
    ]
